### ISSUE TITLE
Test on Linux

### ISSUE THREAD

**Issue by DoubleStyx** [Frozenreflex/Thundagun#10]
I main Windows (yes I'm bad I know), so I'll need to get a Linux setup going to properly test this there. This mod shouldn't introduce any issues beyond what the current Linux build already has.

**Comment by DoubleStyx** [comment]
Anyone who mains Linux, feel free to try it out there.

**Comment by Frozenreflex** [comment]
> Anyone who mains Linux, feel free to try it out there.

Me

**Comment by DoubleStyx** [comment]
Probably gonna close this since it's less of a one-off actionable and more of a continuous goal regarding proper cross-platform testing and validation.
