### ISSUE TITLE
A bunch of things not working (Mute status bar, videoplayers and dashboard)

### ISSUE THREAD

**Issue by darbdarb** [Frozenreflex/Thundagun#32]
![image](https://github.com/user-attachments/assets/0d84b708-f4b9-4d85-8310-81b00eda3699)
Even though i'm unmuted it says im muted, everyone can hear me(rebooting did fix this so this intermittent)
![image](https://github.com/user-attachments/assets/464f1fc2-0ba8-4d25-90f5-e042413d52f0)
Video players seem to not load
![image](https://github.com/user-attachments/assets/28a3ac07-7208-4aae-a64c-d5ba27decdfc)
Dashboard icons fail to load sometimes too :3

i shall provide a log
[DARBDARB - 2024.10.29.1229 - 2024-11-05 20_39_25.log](https://github.com/user-attachments/files/17630591/DARBDARB.-.2024.10.29.1229.-.2024-11-05.20_39_25.log)

**Comment by DoubleStyx** [comment]
Might need to retest to see if this issue is still present. But yes, there are some connectors that are either missing entirely or are missing certain parts. Related to #34.

**Comment by darbdarb** [comment]
UIX still freezes with latest commit, skinmeshrenders fail to load sometimes, particles are pink

**Comment by DoubleStyx** [comment]
Try #42? I just removed the logic for allowing FrooxEngine to run multiple times per frame. This should hopefully address this issue. I think allowing that behavior produced unpredictable behavior as it would break references for various RenderTasks.

**Comment by DoubleStyx** [comment]
Try the latest release. It should prevent FrooxEngine from updating if Unity hasn't processed the changes, which should hopefully prevent UI from breaking.

**Comment by darbdarb** [comment]
> Try the latest release. It should prevent FrooxEngine from updating if Unity hasn't processed the changes, which should hopefully prevent UI from breaking.

Video players still don't load, uix seems alot better 3 hours no freezes except for the voice mute bar
![Untitled video - Made with Clipchamp (1)](https://github.com/user-attachments/assets/a09efda4-e07f-48d1-ba5e-d6976272b1b3)

dashboard icons dont load sometimes unless they get update like getting a message

**Comment by darbdarb** [comment]
skinnedmeshrenders still dont load sometimes too

**Comment by DoubleStyx** [comment]
@Nytra added VideoTextureConnector. Maybe this would help with the video players? https://github.com/Frozenreflex/Thundagun/releases/tag/1.1.0-beta

**Comment by Nytra** [comment]
Yeah videos work now and skinned mesh renderer loading is fixed now too

**Comment by darbdarb** [comment]
> @Nytra added VideoTextureConnector. Maybe this would help with the video players? https://github.com/Frozenreflex/Thundagun/releases/tag/1.1.0-beta

yes this has fixed video players :)

**Comment by Nytra** [comment]
We might be able to close this now. If UIX is still breaking you probably have "Render Incomplete Updates" turned on, try turning it off.

**Comment by DoubleStyx** [comment]
If it's still an issue, this can be reopened later.
