### ISSUE TITLE
Make sure all connectors match the original code

### ISSUE THREAD

**Issue by Nytra** [Frozenreflex/Thundagun#34]
I have found some connectors that are missing some things from the original code that cause it to not work e.g. https://github.com/Frozenreflex/Thundagun/pull/33 for camera portals

I think 3d textures are broken too due to stuff missing from texture connector which I am looking into

Edit: 3d textures fixed

**Comment by Nytra** [comment]
Also, has anyone looked into using reverse patches for the connectors instead of just copying their code 1:1 ?

**Comment by DoubleStyx** [comment]
Aren't reverse patches used when you still need to use the original unedited method? Otherwise you'd either prefix, postfix, transpile, or reimplement.

**Comment by DoubleStyx** [comment]
But yeah a lot of current bugs probably stem from the incomplete connector implementations. Some of them were not originally included because they weren't critical to implement, but we should aim for connector parity when possible.

**Comment by Nytra** [comment]
Well I was thinking that most of the connectors in the mod are basically exact copies of the original connectors, wouldn't it be better to just call the original code in that case? Sorry if I'm not understanding something.

**Comment by Nytra** [comment]
RenderTransformOverride connector needs updating, and also `RenderContextOverride<T>` and RenderMaterialOverride connector need to be added

**Comment by Nytra** [comment]
Skinned mesh renderer and mesh renderer base connectors updated, fixing #8

**Comment by Nytra** [comment]
VideoTextureConnector added in https://github.com/Frozenreflex/Thundagun/pull/49

Known connectors with problems: AudioReverbZone, Particles

**Comment by Nytra** [comment]
Desktop viewer fixed in https://github.com/Frozenreflex/Thundagun/pull/57

Material property blocks will be fixed in https://github.com/Frozenreflex/Thundagun/pull/59

**Comment by Nytra** [comment]
Closing this because it is too vague. If we run into specific bugs we can make issues about those.
