### ISSUE TITLE
VSync Doesn't Work

### ISSUE THREAD

**Issue by DoubleStyx** [Frozenreflex/Thundagun#47]
For some reason Unity doesn't render in VSync when using the mod. Maybe a missing connector or something?

**Comment by Nytra** [comment]
Probably related to the settings not initializing properly https://github.com/Frozenreflex/Thundagun/issues/56

**Comment by DoubleStyx** [comment]
This doesn't happen on the native Linux build for some reason.

**Comment by DoubleStyx** [comment]
This might be because FrooxEngine normally throttles itself or something, rather than using true VSync.

**Comment by DoubleStyx** [comment]
I don't see this issue anymore on Windows/Linux builds, so I'll be closing this unless it becomes an issue again.
