### ISSUE TITLE
Desktop mode avatar view is glitchy

### ISSUE THREAD

**Issue by troyBORG** [Frozenreflex/Thundagun#77]
https://github.com/user-attachments/assets/9b5ca87e-8046-4173-8500-0370ec1fa5a4

**Comment by wisemagick1** [comment]
If I understand right this is the same as #4 . If not, this issue also does occur in VR

**Comment by troyBORG** [comment]
I didn't get a chance to test it in VR yet.

**Comment by DoubleStyx** [comment]
Duplicate of #4

**Comment by troyBORG** [comment]
Yep, I did test it in VR and I am like bobbing up and down and disappearing as I'm moving around.
