### ISSUE TITLE
Interaction Laser is Missing Material

### ISSUE THREAD

**Issue by DoubleStyx** [Frozenreflex/Thundagun#8]
The interaction laser appears pink when using the mod; I suspect it's a missing or misconfigured connector. I'd have to take a closer look at it later.

**Comment by 989onan** [comment]
same with the protoflux tip's color bridge

**Comment by DoubleStyx** [comment]
I think this isn't always present from the start? I think it might be related to how the materialpropertyblocks or material/meshrenderers are handled, as grabbing UI elements usually changes the color of the lasers; here, it causes it to enter an invalid state, rendering as a pink shader/material error.

**Comment by Nytra** [comment]
At least for the protoflux tool it seems to turn pink after the mesh renderer is disabled and then enabled again, you can fix it by setting the material to null and then back to what it was before

**Comment by DoubleStyx** [comment]
Yeah maybe the connector gets a nullreferenceexception or something and stops rendering.

**Comment by DoubleStyx** [comment]
Might be addressed by #34, but I'll keep this open anyway.
