### ISSUE TITLE
Unity Crash on loading into homeworld

### ISSUE THREAD

**Issue by LimeProgramming** [Frozenreflex/Thundagun#80]
Hey there.

I get past the loading screen but as the game loads into my default homeworld (my old one from neos) and before it shows anything of the world I get a unity crash. It Starts bringing up the dashboard. 
I tried it with a few different mods and on it's own, both via the modloader and with monkeypatcher, Behavior was always the same.

Here are the logs of me using just modloader with thundagun, no other mods. 
[LIMESPC - 2024.11.19.479 - 2024-11-27 03_18_01.log](https://github.com/user-attachments/files/17950257/LIMESPC.-.2024.11.19.479.-.2024-11-27.03_18_01.log)

Hope it helps

**Comment by Nytra** [comment]
Can you also post the Player.log from the crash please. https://wiki.resonite.com/Log_Files

Also if you are using Monkey Loader make sure you have updated to the latest version, as it was crashing on startup in the previous version.

**Comment by LimeProgramming** [comment]
yeah, no problem
Here's those logs, generated with monkey loader installed. It is the newest version of monkey loader and I installed it only 2 days ago. 

Again, thundagun is the only mod loaded.

[Player.log](https://github.com/user-attachments/files/17952037/Player.log)
[error.log](https://github.com/user-attachments/files/17952038/error.log
[LIMESPC - 2024.11.19.479 - 2024-11-28 20_00_40.log](https://github.com/user-attachments/files/17952039/LIMESPC.-.2024.11.19.479.-.2024-11-28.20_00_40.log)
)


Hope it helps

**Comment by Nytra** [comment]
It looks like it is crashing when trying the patch the desktop viewer, do you have that turned off or something? Are you on Linux?

**Comment by DoubleStyx** [comment]
Yeah, Linux isn't stable here. I'm on Linux and want to get this working properly, but I haven't had time to debug it yet.

**Comment by DoubleStyx** [comment]
Also are you using the Linux build or the Windows one through Proton?

**Comment by LimeProgramming** [comment]
hey, 
No I'm on windows but I disable desktop tab to help a bit with performance. There's an engine argument for that.

I forgot about that actually. I'll try again with desktop tab enabled.

**Comment by LimeProgramming** [comment]
It's not a monkeyloader thing
The crashing happened with both monkeyloader and RML. Turning on the desktop tab helped. 

I think I'll close this issue because it sounds like this issue is the same/related to the crashing on proton issue. 

Thanks again and good luck!

**Comment by Nytra** [comment]
We can still do something about this, we can skip the desktop patch if the desktop is disabled.

**Comment by Nytra** [comment]
Should be fixed in https://github.com/Frozenreflex/Thundagun/issues/80
