### ISSUE TITLE
Latest Release 1.2.0 Crashing when loading

### ISSUE THREAD

**Issue by NepuShiro** [Frozenreflex/Thundagun#88]
When loading the game, it consistently unity crashes after loading the Settings.
(This is with just LogAutoFlush.dll, and Thundagun.dll loaded)

[NEPNEPSHIRO - 2024.11.19.479 - 2024-11-30 02_48_54.log](https://github.com/user-attachments/files/17964787/NEPNEPSHIRO.-.2024.11.19.479.-.2024-11-30.02_48_54.log)

[Crash_2024-11-30_084920308.zip](https://github.com/user-attachments/files/17964795/Crash_2024-11-30_084920308.zip)

**Comment by Nytra** [comment]
Please try setting your ambient occlusion intensity to a non-zero value
